// Code generated by goctl. DO NOT EDIT.
// goctl {{.version}}

package com.xhb.logic.http.packet.{{.packet}}.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
{{.imports}}

public class {{.className}} extends {{.superClassName}} {

{{.properties}}
{{if .HasProperty}}

	public {{.className}}() {
	}

	public {{.className}}({{.params}}) {
{{.constructorSetter}}
	}
{{end}}

{{.getSet}}
}
