// Code generated by goctl. DO NOT EDIT.

package cache

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	studentFieldNames          = builder.RawFieldNames(&Student{})
	studentRows                = strings.Join(studentFieldNames, ",")
	studentRowsExpectAutoSet   = strings.Join(stringx.Remove(studentFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	studentRowsWithPlaceHolder = strings.Join(stringx.Remove(studentFieldNames, "`type`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheStudentTypePrefix = "cache:student:type:"
)

type (
	studentModel interface {
		Insert(ctx context.Context, data *Student) (sql.Result, error)
		FindOne(ctx context.Context, tp int64) (*Student, error)
		Update(ctx context.Context, data *Student) error
		Delete(ctx context.Context, tp int64) error
	}

	defaultStudentModel struct {
		sqlc.CachedConn
		table string
	}

	Student struct {
		Type       int64           `db:"type"`
		Class      string          `db:"class"`
		Name       string          `db:"name"`
		Age        sql.NullInt64   `db:"age"`
		Score      sql.NullFloat64 `db:"score"`
		CreateTime time.Time       `db:"create_time"`
		UpdateTime sql.NullTime    `db:"update_time"`
		DeleteTime sql.NullTime    `db:"delete_time"`
	}
)

func newStudentModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultStudentModel {
	return &defaultStudentModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`student`",
	}
}

func (m *defaultStudentModel) Delete(ctx context.Context, tp int64) error {
	studentTypeKey := fmt.Sprintf("%s%v", cacheStudentTypePrefix, tp)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `type` = ?", m.table)
		return conn.ExecCtx(ctx, query, tp)
	}, studentTypeKey)
	return err
}

func (m *defaultStudentModel) FindOne(ctx context.Context, tp int64) (*Student, error) {
	studentTypeKey := fmt.Sprintf("%s%v", cacheStudentTypePrefix, tp)
	var resp Student
	err := m.QueryRowCtx(ctx, &resp, studentTypeKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `type` = ? limit 1", studentRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tp)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultStudentModel) Insert(ctx context.Context, data *Student) (sql.Result, error) {
	studentTypeKey := fmt.Sprintf("%s%v", cacheStudentTypePrefix, data.Type)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, studentRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Type, data.Class, data.Name, data.Age, data.Score, data.DeleteTime)
	}, studentTypeKey)
	return ret, err
}

func (m *defaultStudentModel) Update(ctx context.Context, data *Student) error {
	studentTypeKey := fmt.Sprintf("%s%v", cacheStudentTypePrefix, data.Type)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `type` = ?", m.table, studentRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Class, data.Name, data.Age, data.Score, data.DeleteTime, data.Type)
	}, studentTypeKey)
	return err
}

func (m *defaultStudentModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheStudentTypePrefix, primary)
}

func (m *defaultStudentModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `type` = ? limit 1", studentRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultStudentModel) tableName() string {
	return m.table
}
