// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1-alpha

package handler

import (
	"net/http"

	"workspace/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenValidate},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/greet/from/:name",
					Handler: GreetHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithJwtTransition(serverCtx.Config.Trans.PrevSecret, serverCtx.Config.Trans.Secret),
	)
}
