// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "github.com/zeromicro/go-zero/tools/goctl/example/api/test1/internal/handler/login"
	user "github.com/zeromicro/go-zero/tools/goctl/example/api/test1/internal/handler/user"
	"github.com/zeromicro/go-zero/tools/goctl/example/api/test1/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: login.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: user.UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/:id",
				Handler: user.ModifyUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id/fans",
				Handler: user.FansHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/all",
				Handler: user.UserAllHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.UserListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
