// Code generated by goctl. DO NOT EDIT.
package types

type APIRouteGroup struct {
	Jwt         bool        `json:"jwt"`
	Prefix      string      `json:"prefix"`
	Group       string      `json:"group"`
	Timeout     string      `json:"timeout"`
	Middlewares []string    `json:"middlewares"`
	MaxBytes    int64       `json:"maxBytes"`
	Routes      []*APIRoute `json:"routes"`
}

type Range struct {
	Left  int `json:"left"`
	Right int `json:"right"`
}

type FormItem struct {
	Name         string   `json:"name"`
	Type         string   `json:"type"`
	Optional     bool     `json:"optional"`
	EnumValue    []string `json:"enumValue"`
	RangeValue   *Range   `json:"rangeValue"`
	DefaultValue string   `json:"defaultValue"`
}

type Body struct {
	Forms []*FormItem `json:"forms"`
}

type APIRoute struct {
	Method       string `json:"method"`
	Path         string `json:"path"`
	ContentType  string `json:"contentType"`
	RequestBody  *Body  `json:"requestBody"`
	ResponseBody *Body  `json:"responseBody"`
}

type APIGenerateRequest struct {
	Name string           `json:"name"`
	List []*APIRouteGroup `json:"list"`
}

type APIGenerateResponse struct {
}
