// Code generated by goctl. DO NOT EDIT.
package types

type APIGenerateRequest struct {
	Name string      `json:"name"`
	List []*APIRoute `json:"list"`
}

type APIGenerateResponse struct {
}

type APIRoute struct {
	Jwt          bool     `json:"jwt"`
	Prefix       string   `json:"prefix"`
	Group        string   `json:"group"`
	Timeout      string   `json:"timeout"`
	Middlewares  []string `json:"middlewares"`
	MaxBytes     int64    `json:"maxBytes"`
	Method       string   `json:"method"`
	Path         string   `json:"path"`
	ContentType  string   `json:"contentType"`
	RequestBody  *Body    `json:"requestBody"`
	ResponseBody *Body    `json:"responseBody"`
}

type Body struct {
	Forms []*FormItem `json:"forms"`
}

type FormItem struct {
	Name         string   `json:"name"`
	Type         string   `json:"type"`
	Optional     bool     `json:"optional"`
	EnumValue    []string `json:"enumValue"`
	RangeValue   *Range   `json:"rangeValue"`
	DefaultValue string   `json:"defaultValue"`
}

type Range struct {
	Left  int `json:"left"`
	Right int `json:"right"`
}
