// Code generated by goctl. DO NOT EDIT.

export interface Audio {
	id?: string
	duration?: number
	fileExtension?: string
	size?: number
	name?: string
	index?: number
}

export interface ErrWordItem {
	c: string
	s: number
}

export interface HomeworkDataChartRequest {
	homeworkId: string
	subtaskId?: string
}

export interface HomeworkDataChartResponse {
	userNum: number
	averageScore: number
	columns: Array<OralChartDataItem>
}

export interface HomeworkDetailRequest {
	homeworkId: string
}

export interface HomeworkDetailResponse {
	id?: string
	title?: string
	subject?: string // 学科  zh-语文  en-外语  math-数学
	subType: string // 作业类型 recite-背诵  readLoud-朗读
	grade?: string // 年级
	bookVersion?: string // 教材版本
	endTime?: number // 截止时间
	hasCommit: boolean // 是否已提交
	user?: UserInfo
	content?: ResponseContent
	createTime?: number
	updateTime?: number
}

export interface PeriodicHomeworkDetailRequest {
	homeworkId: string
}

export interface PeriodicHomeworkDetailResponse {
	id?: string // 作业id
	title?: string
	subject?: string // 学科  zh-语文  en-外语  math-数学
	subType: string // 作业类型 recite-背诵  readLoud-朗读
	grade?: string // 年级
	bookVersion?: string // 教材版本
	endTime?: number // 截止时间
	user?: UserInfo
	content?: Array<SubtaskContent> // 子任务内容
	createTime?: number
	updateTime?: number
}

export interface HomeworkJoinRequest {
	homeworkId: string
	subtaskId?: string
	disName: string
	oralResultIds: Array<string>
}

export interface HomeworkJoinResponse {
	oralId?: string
}

export interface HomeworkListItem {
	id?: string
	title?: string
	subject?: string // 学科  zh-语文  en-外语  math-数学
	grade?: string // 年级
	bookVersion?: string // 教材版本
	periodic: number // 周期性作业  是：1 否：0
	content?: ResponseContent // 作业内容
	endTime?: number // 截止时间
	user?: UserInfo // 用户信息
	submitCount: number // 教师身份返回，作业提交人数
	averageScore: number // 教师身份返回，作业平均分
	joinStatus?: number // 家长身份返回，提交状态  0-去提交  1-重新提交  在个人的列表里才会有
	level?: number // 家长身份返回，成绩等级   1|2|3|4 对应 ABCD
	submitTask?: number // 家长身份返回，周期性作业提交数量
	totalTask?: number // 家长身份返回，周期性作业总数量
	subType: string
	hasCommit: boolean
	oralId: string
	index: number
	createTime?: number
	updateTime?: number
}

export interface HomeworkOralListItem {
	id?: string
	homeworkId?: string
	user?: UserInfo
	level?: string
	overall: number // 综合分
	audioList?: Array<Audio> // 音频列表
	status?: number // 状态 1-评测中 2-评测成功 3-评测失败
	createTime?: number
}

export interface HomeworkOralListRequest {
	homeworkId: string
	subtaskId?: string
	lastTimestamp: number
	pageSize: number
}

export interface HomeworkOralListResponse {
	hasMore: boolean
	lastTimestamp?: number
	list?: Array<HomeworkOralListItem>
}

export interface HomeworkOralReportRequest {
	homeworkId: string
	subtaskId?: string
}

export interface HomeworkOralReportResponse {
	snapshotId?: string
	joinStatus?: number // 提交状态  0-去提交  1-重新提交  在个人的列表里才会有
	subject?: string
	count?: number
	scoreLevel?: ScoreLevel
	averageDuration: number
	wrongWords?: Array<ErrWordItem>
	averageScore?: AverageScoreItem
}

export interface AverageScoreItem {
	overall: number
	integrity: number
	pron: number
	fluency: number
	errWordNum: number
}

export interface HomeworkOralReportUserListItem {
	oralId?: string
	user?: UserInfo
	overall: number
	integrity: number
	pron: number
	fluency: number
	errWordNum: number
	updateTime?: number
}

export interface HomeworkOralReportUserListRequest {
	homeworkId: string
	subtaskId?: string
	pageSize: number
	lastTimestamp: number
}

export interface HomeworkOralReportUserListResponse {
	hasMore: boolean
	lastTimestamp?: number
	list?: Array<HomeworkOralReportUserListItem>
}

export interface HomeworkUserOralListRequest {
	lastTimestamp: number
	pageSize: number
}

export interface HomeworkUserOralListResponse {
	hasMore?: boolean
	lastTimestamp?: number
	list?: Array<HomeworkOralListItem>
}

export interface OralChartDataItem {
	level?: number
	num: number
}

export interface OralDeleteRequest {
	oralId: string
}

export interface OralDeleteResponse {
}

export interface OralItem {
	oralId?: string
	user?: UserInfo
	status?: number // 1-评测中 2-评测成功 3-测试失败
	overall?: number // 综合分
	pron?: number // 发音得分
	integrity?: number // 完整性得分
	fluency?: number // 流利度得分
	wrongWordNum?: number // 错字数
	duration?: number // 音频时长
}

export interface OralListItem {
	id?: string
	user?: UserInfo
	level?: string
	overall: number
	title: string
	txtSnapshotId?: string
	status?: number // 状态 1-评测中 2-评测成功 3-评测失败
	audioList?: Array<Audio>
	createTime?: number
}

export interface OralListRequest {
	subject?: string // zh-语文  en-外语  math-数学   不传的话就是all
	pageSize: number
	lastTimestamp: number
}

export interface OralListResponse {
	hasMore: boolean
	lastTimestamp?: number
	count?: number
	list?: Array<OralListItem>
}

export interface OralReportRequest {
	oralId: string
}

export interface OralReportResponse {
	id?: string
	subject?: string
	status?: number
	level?: string
	user: UserInfo
	type?: string // myself-自主练  homework-口语作业
	homeworkId?: string
	subtaskId?: string
	comment: string // 快捷评语
	txtSnapshotId?: string
	subType: string
	oralResult?: Array<OralResult>
	errWordNum: number
	createTime?: number
}

export interface OralResult {
	sectionId?: string // 段落ID
	wordId?: string // 词句ID
	words?: Array<OralWord>
	score?: OralScore
	audio?: Audio
}

export interface OralSaveRequest {
	oralId?: string
	snapshotId: string
	subject: string
	grade: string
	subType: string // 练习方式 recite-背诵  readLoud-朗读
	bookVersion: string
	disName: string // 显示名字
	oralResultIds: Array<string>
}

export interface OralSaveResponse {
	oralId: string
}

export interface OralScore {
	overall: number
	integrity: number
	pron: number
	fluency: number
}

export interface OralWord {
	w?: string
	s: number
	c?: string
}

export interface PublishHomeworkRequest {
	title: string
	subject: string // 学科  zh-语文  en-外语  math-数学
	grade: string // 年级
	bookVersion: string // 教材版本
	subType: string // 作业类型 recite-背诵  readLoud-朗读
	endTime: number // 截止时间
	signature: string // 署名
	content: RequestContent
}

export interface PublishHomeworkResponse {
	homeworkId?: string
}

export interface PublishPeriodicHomeworkRequest {
	title: string
	subject: string // 学科  zh-语文  en-外语  math-数学
	grade: string // 年级
	bookVersion: string // 教材版本
	subType: string // 作业类型 recite-背诵  readLoud-朗读
	endTime: number // 截止时间
	signature: string // 署名
	content: Array<RequestContent>
}

export interface PublishPeriodicHomeworkResponse {
	homeworkId?: string
}

export interface RequestContent {
	index?: number // 周期性作业文章顺序
	unit?: string // 周期性作业，子任务传入单元名
	title?: string // 周期性作业，子任务传入文章名
	txtId: string // 翰林院文章ID
	sections: Array<Section> // 段落
}

export interface ResponseContent {
	txtSnapshotId: string // 翰林院文章ID
	sections?: Array<Section> // 段落
}

export interface SubtaskContent {
	index: number // 文章顺序
	subtaskId: string
	txtSnapshotId: string // 翰林院文章ID
	sections?: Array<Section> // 段落
	unit?: string // 单元名
	title?: string // 文章名
	submitCount: number // 教师身份返回，作业提交人数
	hasCommit: boolean // 家长身份返回，是否已提交
	oralId?: string // 家长身份返回，我提交的成果Id
	level?: number // 家长身份返回，成绩等级   1|2|3|4 对应 ABCD
}

export interface ScoreLevel {
	overall?: ScoreItem
	integrity?: ScoreItem
	pron?: ScoreItem
	fluency?: ScoreItem
}

export interface ScoreItem {
	score: number
	scoreStatistics: ScoreStatisticsItem
	scoreLevel: ScoreLevelItem
}

export interface ScoreStatisticsItem {
	max: number
	min: number
	average: number
}

export interface ScoreLevelItem {
	l1: number
	l2: number
	l3: number
	l4: number
}

export interface Section {
	id?: string // 段落ID
}

export interface UserInfo {
	id?: string
	displayName: string
	avatar: string
}

export interface MpBindMobileRequest {
	encryptedData: string
	iv: string
}

export interface MpLoginRequest {
	authCode: string
}

export interface MpLoginResponse {
	userId: string
	userName: string
	mobile: string
	hasBindMobile: boolean
	openId: string
	accessToken: string
	role: string // 身份 空字符串为未设置过身份 TEACHER-教师 | PARENT-家长
	hasPublished: boolean
}

export interface MpSwitchRoleRequest {
	role: string // 身份 TEACHER-教师 | PARENT-家长
}

export interface WxPublicResp {
	follow: boolean // 是否关注过公众号
}

export interface ResultParseRequest {
	id: string
	subject: string
	platform: string // 评测平台  singsound-先声 chivox-驰声
	type: string // myself-自主练   homework-作业
	audio: Audio
	sectionId: string // 段落ID 必传
	wordId?: string // 词句ID 没有话可以不传
	status: number // 1-评测中  2-评测成功  3-评测失败
	resultJson: string
}

export interface ResultParseResponse {
	oralResultId: string
	oralResult: OralResult
}

export interface UserSignatureRequest {
	typeName: string
}

export interface UserSignatureResponse {
	displayName: string
}

export interface SubmitCountRequest {
}

export interface SubmitCountRequestParams {
	homeworkId: string
	subtaskId: string
}

export interface SubmitCountResponse {
	count?: number
}

export interface UndoRequest {
	homeworkId: string
}

export interface UndoResponse {
}

export interface ExperienceResult {
	audio: Audio
	sectionId: string // 段落ID 必传
	wordId?: string // 词句ID 没有话可以不传
	status: number // 1-评测中  2-评测成功  3-评测失败
	resultJson: string
}

export interface ExperienceRequest {
	subject: string
	platform: string // 评测平台  singsound-先声 chivox-驰声
	results: Array<ExperienceResult>
}

export interface ExperienceResponse {
	subject?: string
	level?: string
	comment: string
	type?: string // myself-自主练  homework-口语作业
	txtSnapshotId?: string
	subType: string
	errWordNum: number
	oralResult?: Array<OralResult>
}

export interface ExperienceArticleResponse {
	zh: Text
	en: Text
}

export interface Text {
	txtId: string
	title: string
	author: string
	bookId: number
	chapterId: number
	context: string
	audioUrl: string
	audioDuration: number
	imageUrl: string
	tagId: number
	tagName: string
	status: number
	contentType: number
	parentId: string
	originId: string
	isRecite: number
	contentChild: Array<TextL1>
}

export interface TextL1 {
	txtId: string
	title: string
	context: string
	audioUrl: string
	audioDuration: number
	imageUrl: string
	status: number
	contentType: number
	parentId: string
	originId: string
	isRecite: number
	contentChild: Array<TextL2>
}

export interface TextL2 {
	txtId: string
	context: string
	audioUrl: string
	audioDuration: number
	imageUrl: string
	status: number
	contentType: number
	parentId: string
	originId: string
	isRecite: number
}

export interface RoleListRequest {
	role: string
	pageSize: number
	lastTimestamp: number
}

export interface RoleListResponse {
	hasMore: boolean
	lastTimestamp?: number
	list?: Array<HomeworkListItem>
}

export interface ShowStripResponse {
	show: boolean // 是否显示复习资料包MVP
}

export interface Color {
	r: string
	g: string
	b: string
}

export interface GetwxacodeRequest {
	scene: string
	page?: string
	width?: number
	auto_color?: boolean
	line_color?: Color
	is_hyaline?: boolean
}

export interface GetwxacodeResponse {
	buffer: Blob
}

export interface GetPosterRequest {
}

export interface GetPosterRequestParams {
	userId: string
}

export interface GetPosterResponse {
	days: number
	emoji: string
	saying: string
	backPicture: string
}

export interface GetBookUrlRequest {
}

export interface GetBookUrlRequestParams {
	bookId: number
}

export interface GetBookUrlResponse {
	url: string
	name: string
}

