package util

var headTemplate = `// Code generated by goctl. DO NOT EDIT!
// Source: {{.source}}`

func GetHead(source string) string {
	buffer, _ := With("head").Parse(headTemplate).Execute(map[string]interface{}{
		"source": source,
	})
	return buffer.String()
}
