// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1-alpha

package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
