// Code generated by goctl. DO NOT EDIT.
package types

import (
{{if .containsTime}}
	"time"
{{end}}
{{if ne .importPackages ""}}
    {{.importPackages}}
{{end}}
)

{{if ne .vars ""}}
var(
    {{.vars}}
)
{{end}}

{{.types}}

{{.typeFuncValidators}}