// Code generated by goctl. DO NOT EDIT.
// goctl {{.version}}

package types{{if or .containsTime .containsFile}}
import ({{if .containsTime}}
	"time"{{end}}{{if .containsFile}}
	"mime/multipart"{{end}}
){{end}}
{{.types}}
