package util

import "github.com/lerity-yao/go-zero/tools/cztctl/internal/version"

const (
	// DoNotEditHead added to the beginning of a file to prompt the user not to edit
	DoNotEditHead = "// Code generated by cztctl. DO NOT EDIT."

	headTemplate = DoNotEditHead + `
// cztctl {{.version}}
// Source: {{.source}}`
)

// GetHead returns a code head string with source filename
func GetHead(source string) string {
	buffer, _ := With("head").Parse(headTemplate).Execute(map[string]any{
		"source":  source,
		"version": version.BuildVersion,
	})
	return buffer.String()
}
