package migrationnotes

import (
	"fmt"
	"io/ioutil"
	"strings"

	"github.com/urfave/cli"
	"github.com/zeromicro/go-zero/tools/goctl/util/i18n"
)

func migrateBefore1_3_4(ctx *cli.Context) error {
	// TODO: Hard-coded arguments should be eliminated
	dir := ctx.String("dir")
	style := ctx.String("style")
	ok, err := needShow1_3_4(dir, style)
	if err != nil {
		return err
	}
	if !ok {
		return nil
	}

	if i18n.IsCN {
		fmt.Println(`似乎您的 goctl 刚刚升级到 1.3.4 以后的版本，该版本对 model 模块的代码做了重构。原有的 XXXmodel.go 分离成了 XXXmodel_gen.go（只读） 和 XXXmodel.go 两部分。 您只需按照以下步骤操作，即可完成迁移：
1. 把原有的 XXXmodel.go 备份（确保该文件名不再在当前目录）
2. 重新执行生成命令（此时会生成新的 XXXmodel.go）
3. 将其中不属于 goctl 生成的代码依据 XXXmodel_gen.go 中的注释提示填充到 XXXmodel.go中`)
	} else {
		fmt.Println(`It seems like that your goctl has just been upgraded to version 1.3.4 or later, which refactored the code of the model module. The original XXXmodel.go has been split into XXXmodel_gen.go (read-only) and XXXmodel.go. You just need to follow these steps to complete the migration:
1. back up the original XXXmodel.go (make sure the file name is no longer in the current directory)
2. re-run the generate command (a new XXXmodel.go will be created)
3. populate XXXmodel.go with the code that is not generated by goctl according to the comments in XXXmodel_gen.go`)
	}

	return nil
}

func needShow1_3_4(dir, style string) (bool, error) {
	files, err := ioutil.ReadDir(dir)
	if err != nil {
		return false, nil
	}
	// Returns false when the directory contains a file with the suffix "_gen.go"
	// In addition, it returns true if it contains a model file extension.
	// In other case, false is returned.
	for _, f := range files {
		if f.IsDir() {
			continue
		}
		if strings.HasSuffix(f.Name(), "_gen.go") {
			return false, nil
		}
	}
	modelSuffix, err := getModelSuffix(style)
	if err != nil {
		return false, err
	}
	for _, f := range files {
		if !f.IsDir() && strings.HasSuffix(f.Name(), modelSuffix) {
			return true, nil
		}
	}
	return false, nil

}
