// Code generated by goctl. DO NOT EDIT.
package types

type UserBase struct {
	ID       string            `json:"id"` // The user id.
	Name     string            `json:"name"`
	Nickname string            `json:"nickname"`
	Habbits  []string          `json:"habbits"`
	Extra    map[string]string `json:"extra"` // The user extra info.
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Base
	UserBase
	ExpireToken string `json:"expire_token"`
	ExpiresAt   string `json:"expires_at"` // The token expires at.
}

type GetUserInfoRequest struct {
	ID string `path:"id"`
}

type GetUserInfoResponse struct {
	Base
	Data *UserBase `json:"data"`
}

type ModifyUserInfoRequest struct {
	ID       string            `path:"id"`
	Name     string            `json:"name"`
	Nickname string            `json:"nickname"`
	Habbits  []string          `json:"habbits"`
	Extra    map[string]string `json:"extra"`
}

type ModifyUserInfoResponse struct {
	Base
}

type FansRequest struct {
	ID   string `path:"id"`
	Page int    `form:"page"`
	Size int    `form:"size"`
}

type FansResponse struct {
	Base
	Total       int         `json:"total"`
	CurrentPage int         `json:"current_page"`
	Data        []*UserBase `json:"data"`
}

type UserListRequest struct {
	Page int `form:"page"`
	Size int `form:"size"`
}

type Base struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}
